version: "3.8"
services: 
  app:
    build:
      context: .
    volumes:
      - .:/bfi-app-react
    ports: 
      - 3000:3000
    image: app:bfi-app-react
    container_name: react_container
    command: npm start